apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kube-state-metrics-serviceaccount.yaml
  - kube-state-metrics-clusterrole.yaml
  - kube-state-metrics-clusterrolebinding.yaml
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-service.yaml
  - victoriametrics-deployment.yaml
  - victoriametrics-service.yaml
  - mimir-configmap.yaml
  - mimir-deployment.yaml
  - mimir-service.yaml
  - vmagent-configmap.yaml
  - vmagent-deployment.yaml
  - vmagent-service.yaml
  - tempo-configmap.yaml
  - tempo-deployment.yaml
  - tempo-service.yaml
  - loki-configmap.yaml
  - loki-deployment.yaml
  - loki-service.yaml
  - promtail-configmap.yaml
  - promtail-serviceaccount.yaml
  - promtail-clusterrole.yaml
  - promtail-clusterrolebinding.yaml
  - promtail-daemonset.yaml
  - grafana-datasources-configmap.yaml
  - grafana-dashboard-providers-configmap.yaml
  - grafana-fastapi-dashboard-configmap.yaml
  - grafana-control-plane-dashboard-configmap.yaml
  - grafana-k6-dashboard-configmap.yaml
  - grafana-storage-comparison-dashboard-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
