apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: service-launchpad-observability
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: service-launchpad
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /var/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        cache_ttl: 24h
      filesystem:
        directory: /var/loki/chunks
    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    ruler:
      alertmanager_url: http://localhost:9093
      storage:
        type: local
        local:
          directory: /var/loki/rules
    compactor:
      working_directory: /var/loki/compactor
      delete_request_store: filesystem
      retention_enabled: true
    limits_config:
      max_query_lookback: 24h
      retention_period: 24h
