apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-launchpad-promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: service-launchpad
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
