apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: service-launchpad-observability
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/component: metrics-store
    app.kubernetes.io/part-of: service-launchpad
spec:
  selector:
    app.kubernetes.io/name: victoriametrics
  ports:
    - name: http
      port: 8428
      targetPort: http
  type: ClusterIP
