apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: service-launchpad-dev
  labels:
    app.kubernetes.io/name: fastapi-service
    app.kubernetes.io/component: inference-simulator
    app.kubernetes.io/part-of: service-launchpad
spec:
  selector:
    app.kubernetes.io/name: fastapi-service
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
